services:
  backend:
    image: geohod-backend:latest
    container_name: geohod-backend
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - geohod-net

  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: geohod-postgres
    restart: always
    env_file: .env
    volumes:
      - geohod-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - geohod-net

volumes:
  geohod-postgres-data:

networks:
  geohod-net: