services:
  certbot:
    image: docker.io/certbot/certbot:latest
    container_name: frontend-certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --standalone --email idemozajedno@yandex.ru --agree-tos --no-eff-email -d app.geohod.ru; while :; do certbot renew; sleep 12h & wait $!; done;'"
    volumes:
      - certbot_certs:/etc/letsencrypt
    network_mode: host
    restart: on-failure

  nginx:
    image: docker.io/library/nginx:latest
    container_name: frontend-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_certs:/etc/letsencrypt
    networks:
      - geohod-net
    depends_on:
      - certbot

volumes:
  certbot_certs:

networks:
  geohod-net:
    external: true