services:
  nginx:
    image: docker.io/library/nginx:latest
    container_name: frontend-nginx-unified
    restart: always
    command: /bin/sh -c "while [ ! -f /etc/letsencrypt_dev/live/dev.geohod.ru/fullchain.pem ] || [ ! -f /etc/letsencrypt_prod/live/app.geohod.ru/fullchain.pem ]; do echo 'Waiting for certificates...'; sleep 2; done; nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist/dev:/usr/share/nginx/html/dev:ro
      - ./dist/prod:/usr/share/nginx/html/prod:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_certs_dev:/etc/letsencrypt_dev
      - certbot_certs:/etc/letsencrypt_prod
    networks:
      - geohod-net-dev
      - geohod-net

volumes:
  certbot_certs_dev:
    external: true
  certbot_certs:
    external: true

networks:
  geohod-net-dev:
    external: true
  geohod-net:
    external: true