name: Deploy Frontend (Unified)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production
          - both

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Development
        if: ${{ github.event.inputs.environment == 'development' || github.event.inputs.environment == 'both' }}
        run: npm run build
        env:
          REACT_APP_TELEGRAM_WEBAPP: true
          REACT_APP_API_URL: https://dev.geohod.ru/api/v1
          REACT_APP_BOT_USERNAME: geohoddev_bot

      - name: Transfer dev assets to VPS
        if: ${{ github.event.inputs.environment == 'development' || github.event.inputs.environment == 'both' }}
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/"
          target: "~/frontend-app-unified/dist/dev/"
          strip_components: 1

      - name: Build Production
        if: ${{ github.event.inputs.environment == 'production' || github.event.inputs.environment == 'both' }}
        run: npm run build
        env:
          REACT_APP_TELEGRAM_WEBAPP: true
          REACT_APP_API_URL: https://app.geohod.ru/api/v1
          REACT_APP_BOT_USERNAME: geohodton_bot

      - name: Transfer prod assets to VPS
        if: ${{ github.event.inputs.environment == 'production' || github.event.inputs.environment == 'both' }}
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/"
          target: "~/frontend-app-unified/dist/prod/"
          strip_components: 1

      - name: Transfer unified deployment files
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "deployment/unified/*"
          target: "~/frontend-app-unified/"
          strip_components: 2

      - name: Execute remote setup
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd ~/frontend-app-unified
            chmod +x install.sh
            chmod +x certbot.sh
            ./install.sh